server:
  port: 8080

spring:
  application:
    name: stock-premium-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-a8acby50.sql.tencentcdb.com:20096/stock_premium?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: hjyroot
    password: 1q2w3eHjy~
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      connection-test-query: SELECT 1

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.stock.premium: info
    org.springframework.web: info
  file:
    name: logs/stock-premium.log

schedule:
  stock-data-collect:
    enabled: true
  daily-stats:
    enabled: true

# 定时任务配置
stock:
  scheduler:
    enabled: true
    stock-price-cron: "0 */1 * * * ?" # 每1分钟执行一次
    exchange-rate-cron: "0 0 9,15 * * ?" # 每天9点和15点执行
