# Spring Boot 数据源配置 - 连接CloudBase MySQL
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-a8acby50.sql.tencentcdb.com:20096/stock_premium?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: hjyroot
    password: 1q2w3eHjy~
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      connection-test-query: SELECT 1

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

# CloudBase MySQL 配置（用于同步工具）
cloudbase:
  mysql:
    url: jdbc:mysql://sh-cynosdbmysql-grp-a8acby50.sql.tencentcdb.com:20096/stock_premium?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: hjyroot
    password: 1q2w3eHjy~
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日志配置
logging:
  level:
    com.stock.premium: DEBUG
    com.stock.premium.utils.CloudBaseSyncUtil: DEBUG
    com.stock.premium.controller.CloudBaseSyncController: DEBUG
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
