server:
  port: 8080

spring:
  application:
    name: stock-premium-system
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      enabled: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.stock.premium: info

schedule:
  stock-data-collect:
    enabled: false
  daily-stats:
    enabled: false